# Generated by Django 2.1.5 on 2020-02-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_left',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
